name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: docker
    container:
      image: data.forgejo.org/oci/docker:cli   # has docker CLI built in
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Codeberg container registry
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ vars.CODEBERG_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            codeberg.org/alessandro_battini/trovekeep:latest
            codeberg.org/alessandro_battini/trovekeep:${{ github.ref_name }}
